version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3030:3030"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "5433:5432" # Expose PostgreSQL on port 5433, Change if needed
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb/DB.sql:/docker-entrypoint-initdb.d/DB.sql:ro

volumes:
  pgdata:
