FROM node:18-alpine

WORKDIR /app

# Copia package.json y lock para instalar dependencias
COPY package*.json ./

# Instala dependencias
RUN npm install

# Copia carpeta Prisma y genera cliente
COPY prisma ./prisma
RUN npx prisma generate

# Copia el resto del código
COPY . .

# Exponer puerto
EXPOSE 3030

# Comando de desarrollo (usa tu script en package.json)
CMD ["npm", "run", "dev"]
